### ISSUE TITLE
Using the confuser interface for quiz creation

### ISSUE THREAD

**Issue by phoebem** [capstone-lingo-2016/open-fluency2#11]

**Comment by MattSilva** [comment]
I have added the ability to create a confuser quiz. The bootstrap.groovy file in the development branch currently creates quizzes using confusers. There is a createConfuserQuestion method added to the quizService.

Currently the quizzes have to be created manually in the bootstrap.groovy file. The functionality allowing users to create confuser quizzes in the app hasn't been added yet because we need to wait for the new quiz editor and quiz import functionality first.
