### ISSUE TITLE
Customization is broken

### ISSUE THREAD

**Issue by phoebem** [capstone-lingo-2016/open-fluency2#78]
When you edit a flashcard and select a new picture and save the card, it does not use the new image,
On a macbook (don't know about windows), when you choose to share the microphone to record, it pops up a menu to share microphone, if you select that, it has no effect. The start recording button will just pop up the menu again.

**Comment by MattSilva** [comment]
I fixed the image part of this in commit 89f1ec4576b32ab73140090592d091978c6193b5.

**Comment by MattSilva** [comment]
I removed the audio customization feature in commit 419a654a01a296a778978467ff3f6804d54b70c8

When we discussed our design with the professor, he told us that he would prefer if we remove the ability for students to record their own pronunciation audio for flashcards since it would be better if the students listened to the audio provided by the instructor. The reason being that the student's pronunciation recording could be incorrect.
